name: rbd_app
description: "A new Flutter project."
publish_to: 'none'

version: 0.0.3+7

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.4.4
  image_picker: ^1.1.2
  video_player: ^2.2.19
  http: ^1.3.0
  logger: ^2.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
